name: nullfsvfs CI on ubuntu-latest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: abbbi/github-actions-tune@v1
    - name: Install build-essential and devscripts
      run: sudo apt-get install build-essential devscripts equivs acl
    - name: Install Kernel Build Dependencies
      run: sudo mk-build-deps --install debian/control
    - name: Remove dependency package
      run: rm -f nullfsvfs-build-deps*.deb
    - name: Build Debian package
      run: sudo -E dpkg-buildpackage -uc -us -b
    - name: Install generated Package
      run: sudo dpkg -i ../nullfsvfs_*_amd64.deb
    - name: Modprobe kernel module
      run: sudo modprobe nullfs
    - name: Mount nullfs
      run: sudo mount -t nullfs none /mnt
    - name: Copy files to nullfs
      run: sudo cp -r /etc/ /mnt/
    - name: Test acl
      run: |
        sudo mkdir /mnt/acl_dir
        sudo touch /mnt/acl_file
        sudo setfacl -m d:u:root:r /mnt/acl_dir
        sudo setfacl -m u:root:r /mnt/file
    - name: Test O_DIRECT
      run: sudo dd if=/dev/zero of=/mnt/direct bs=1M count=1953 oflag=direct
    - name: Umount nullfs
      run: sudo umount /mnt
