name: nullfsvfs CI on ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build-essential and devscripts
      run: sudo apt-get install build-essential devscripts equivs
    - name: Install Kernel Build Dependencies
      run: sudo mk-build-deps --install debian/control
    - name: Build Debian package
      run: dpkg-buildpackage -rfakeroot --no-sign
    - name: Install Package
      run: sudo dpkg -i ../nullfsvfs_*_amd64.deb
    - name: Modprobe kernel module
      run: sudo modprobe nullfs
    - name: Mount nullfs
      run: sudo mount -t nullfs none /mnt
    - name: Copy files to nullfs
      run: sudo cp -r /etc/ /mnt/
    - name: Umount nullfs
      run: sudo umount /mnt
